node cookies.js https://www.site1.com/al/
node cookies.js https://www.site1.com/at/
node cookies.js https://www.site1.com/az/
node cookies.js https://www.site1.com/be/
node cookies.js https://www.site1.com/ba/
node cookies.js https://www.site1.com/bg/
node cookies.js https://www.site1.com/hr/
node cookies.js https://site1.com.cy/
node cookies.js https://www.site1.com/cz/
node cookies.js https://www.site1.com/dk/
node cookies.js https://www.site1.ee/
node cookies.js https://www.site1.com/fi/
node cookies.js https://www.site1.com/fr/
node cookies.js https://www.site1.com/ge
node cookies.js https://www.site1.com/de/
node cookies.js https://www.site1.com/gi/
node cookies.js https://www.site1.com/gr/
node cookies.js https://www.site1.com/hu/
node cookies.js https://www.site1.com/is/
node cookies.js https://www.site1.com/ie/
node cookies.js https://www.site1.com/it/
node cookies.js https://www.site1.com/lv/
node cookies.js https://www.site1.com/lt/
node cookies.js https://www.site1.com/lu/
node cookies.js https://www.site1.com/mt/
node cookies.js https://www.site1.com/me/
node cookies.js https://www.site1.com/nl/
node cookies.js https://www.site1.com/no/
node cookies.js https://www.site1.com/pl/
node cookies.js https://www.site1.com/pt/
node cookies.js https://www.site1.com/ro/
node cookies.js https://www.site1.com/rs/
node cookies.js https://www.site1.com/sk/
node cookies.js https://www.site1.com/es/
node cookies.js https://www.site1.com/si/
node cookies.js https://www.site1.com/se/
node cookies.js https://www.site1.com/ch/
node cookies.js https://www.site1.com/tr
node cookies.js https://www.site1.com/ua
node cookies.js https://www.site1.com/uk/
